apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.flaskAppName" . }}
  labels:
    app: {{ include "mychart.flaskAppName" . }}
spec:
  type: {{ .Values.flaskApp.service.type }}
  ports:
    - port: {{ .Values.flaskApp.service.port }}
      targetPort: {{ .Values.flaskApp.service.port }}
      {{- if eq .Values.flaskApp.service.type "NodePort" }}
      nodePort: {{ .Values.flaskApp.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "mychart.flaskAppName" . }}
