apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.mysqlPVCName" . }}
  labels:
    app: {{ include "mychart.mysqlName" . }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
