apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.mysqlName" . }}
  labels:
    app: {{ include "mychart.mysqlName" . }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mychart.mysqlName" . }}
  template:
    metadata:
      labels:
        app: {{ include "mychart.mysqlName" . }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.database }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.user }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.password }}"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "{{ .Values.mysql.resources.requests.memory }}"
              cpu: "{{ .Values.mysql.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.mysql.resources.limits.memory }}"
              cpu: "{{ .Values.mysql.resources.limits.cpu }}"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "mychart.mysqlPVCName" . }}
        - name: init-scripts
          configMap:
            name: {{ include "mychart.mysqlConfigMapName" . }}
